### ISSUE TITLE
Simplify the military affidavit page

### ISSUE THREAD

**Issue by nava-ebad** [SuffolkLITLab/docassemble-MATCSmallClaims#36]
Break up the text to avoid making it long. Have "I don't know" bring you to a separate page that provides ways to figure it out and THEN check if the user still doesn't know.

**Comment by samglover** [comment]
For each party, ask whether the user knows if they are in the military.

If **yes**, ask how they know:
1. SCRA website
2. Internet search
3. Confirmed by the military
4. Personal knowledge (give a text box)

If **no**, give them a link to resources (SCRA website, other?) and then ask again if they really don't know.

**Comment by samglover** [comment]
Keeping as a question because we'll want the trial court's feedback on the solution.
