### ISSUE TITLE
Is a military affidavit required for a business?

### ISSUE THREAD

**Issue by samglover** [SuffolkLITLab/docassemble-MATCSmallClaims#40]
For example, if the owner/dba is in the military?

**Comment by samglover** [comment]
@nava-ebad or @MarkMarotta0 do you remember what the answer to this was?

**Comment by MarkMarotta0** [comment]
> @nava-ebad or @MarkMarotta0 do you remember what the answer to this was?

I do not know for certain, but I believe the affidavit was required for businesses.

**Comment by nicoledimitri** [comment]
The plaintiff must verify the military status of the individual(s) who own the business that (s)he is suing. The SCRA recommends using its designated data center to confirm. The plaintiff must complete the Military Affidavit in its entirety/affirmatively when the primary owner or manager of the defendant business is actively serving in the military.
