### ISSUE TITLE
Identify the forms that should be part of the small claims interview.

### ISSUE THREAD

**Issue by samglover** [SuffolkLITLab/docassemble-MATCSmallClaims#5]

**Comment by samglover** [comment]
According to @MarkMarotta0 the existing guided interview generates more PDFs than just the statement of claim and next steps documents. @nonprofittechy Is there already a list of documents that should be included somewhere or do we need to create one?

**Comment by nonprofittechy** [comment]
@colarusso may know. I wasn't part of this conversation with the trial court

**Comment by samglover** [comment]
Closing because now that I have updated #3 I think this issue is duplicative.
