### ISSUE TITLE
Only show the information about business names if the user selects "Business or organization" on the "names of opposing" parties screen

### ISSUE THREAD

**Issue by MarkMarotta0** [SuffolkLITLab/docassemble-MATCSmallClaims#79]
defendant first page = yesnoradio (person or business) 
defendant second page = includes text about how to research defendant

**Comment by samglover** [comment]
I think what this means is that for each defendant, we need to ask:

1. Are they a person or a business?
2. Contact information
3. Are they in the military and how does the user know? (Include information about researching their military status.)

Also, see #40

**Comment by samglover** [comment]
The subquestion/info text should show up below the radio buttons and above the field for the name of the business. Or it might work better to put that information on a subsequent page.
