### ISSUE TITLE
Calculate the filing fee based on the amount of the claim and show it to the user

### ISSUE THREAD

**Issue by MarkMarotta0** [SuffolkLITLab/docassemble-MATCSmallClaims#81]
- [x] Calculate the filing fee
- [x] Update copy according to the [court's feedback](https://sumail.sharepoint.com/:b:/r/sites/LITFellowsClinic/Shared%20Documents/MATC%20small%20claims%20complaint/2024-08-19%20feedback%20on%20small%20claims%20complaint%20interview/Guide%20n%20File_PAGE%205_Draft%20V2.pdf?csf=1&web=1&e=VrosXe)

**Comment by samglover** [comment]
Use the filing fee table on the **Small_claims** screen (after double-checking the numbers with the court!).

**Comment by samglover** [comment]
Will also need to update the page copy on the same screen.

**Comment by nonprofittechy** [comment]
FYI - the e-filing code can help with calculating fees, but it may not be as user friendly as what you can do here, so it's not necessarily in conflict.
