### ISSUE TITLE
Clarify asterisk on court selection page 

### ISSUE THREAD

**Issue by MarkMarotta0** [SuffolkLITLab/docassemble-MATCSmallClaims#82]
Move the asterisk so the user does not think they also have to choose from the dropdown in addition to the recommended courts

**Comment by samglover** [comment]
The court pointed out that the asterisk remains even after the user has selected a court. This is normal behavior for an online form (*required* labels don't go away when information is entered), but something about this select does seem a little off. Maybe it can be improved.
