### ISSUE TITLE
Update interview to reflect upcoming changes in Small Claims law.

### ISSUE THREAD

**Issue by nicoledimitri** [SuffolkLITLab/docassemble-MATCSmallClaims#91]

**Comment by samglover** [comment]
@nicoledimitri Is there a specific change you had in mind for this issue?

**Comment by nicoledimitri** [comment]
No, I just recall the Trial Court analysts mentioning that there would be changes to the Small Claims process next year. I put a note here just in case they informed us of specific changes that would affect the interview.
